on:
  push:
    branches:
      - release
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam build -u
      - run: sam deploy --stack-name demo-display-lambda --resolve-s3 --s3-prefix demo-display-lambda --tags service-group=demo service-name=display-lambda--no-confirm-changeset --no-fail-on-empty-changeset
  